# Generated by Django 5.1.15 on 2026-07-23 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Maqola sarlavhasini kiriting', max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug (URL kaliti)')),
                ('content', models.TextField(verbose_name='Maqola matni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan')], default='published', max_length=10, verbose_name='Holati')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
